Repository kakao-tech-campus-2nd-step3/Team10_BE, pull requests merged in 2024-09, with the labels that each got.

#4 ExceptionAdvice 정의
  build.gradle
  src/main/java/poomasi/global/error/ApplicationError.java
  src/main/java/poomasi/global/error/ApplicationException.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/error/BusinessException.java
  src/main/java/poomasi/global/error/ExceptionAdvice.java
Labels: 👋 show my code, feature

#19 Farm 엔티티를 개발한다
  .gitignore
  build.gradle
  src/main/java/poomasi/domain/farm/controller/FarmController.java
  src/main/java/poomasi/domain/farm/controller/FarmFarmerController.java
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/dto/FarmResponse.java
  src/main/java/poomasi/domain/farm/dto/FarmUpdateRequest.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/farm/entity/FarmStatus.java
  src/main/java/poomasi/domain/farm/repository/FarmRepository.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/farm/service/FarmService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🎉 feature, 🤨 P1, 📉 DDL Required

#20 멤버 인증 인가
  .gitignore
  build.gradle
  src/main/java/poomasi/Application.java
  src/main/java/poomasi/domain/auth/controller/AuthController.java
  src/main/java/poomasi/domain/auth/dto/request/LoginRequest.java
  src/main/java/poomasi/domain/auth/dto/response/TokenResponse.java
  src/main/java/poomasi/domain/auth/entity/RefreshToken.java
  src/main/java/poomasi/domain/auth/service/AuthService.java
  src/main/java/poomasi/domain/auth/service/RefreshTokenService.java
  src/main/java/poomasi/domain/member/entity/LoginType.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/member/entity/MemberProfile.java
  src/main/java/poomasi/domain/member/entity/Role.java
  src/main/java/poomasi/domain/member/repository/MemberRepository.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/redis/config/RedisConfig.java
  src/main/java/poomasi/global/redis/service/RedisService.java
  src/main/java/poomasi/global/util/JwtProvider.java
  src/main/resources/application-secret.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🎉 feature, 🤨 P1
