Repository kakao-tech-campus-2nd-step3/Team10_BE, pull requests merged in 2024-11, with the labels that each got.

#83 order/payment domain
  build.gradle
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/order/_payment/config/IamportConfig.java
  src/main/java/poomasi/domain/order/_payment/controller/PaymentController.java
  src/main/java/poomasi/domain/order/_payment/dto/request/PaymentPreRegisterRequest.java
  src/main/java/poomasi/domain/order/_payment/dto/request/PaymentWebHookRequest.java
  src/main/java/poomasi/domain/order/_payment/dto/response/PaymentPreRegisterResponse.java
  src/main/java/poomasi/domain/order/_payment/dto/response/PaymentResponse.java
  src/main/java/poomasi/domain/order/_payment/entity/Payment.java
  src/main/java/poomasi/domain/order/_payment/entity/PaymentMethod.java
  src/main/java/poomasi/domain/order/_payment/entity/PaymentState.java
  src/main/java/poomasi/domain/order/_payment/repository/PaymentRepository.java
  src/main/java/poomasi/domain/order/_payment/service/PaymentService.java
  src/main/java/poomasi/domain/order/_refund/entity/Refund.java
  src/main/java/poomasi/domain/order/_refund/entity/RefundStatus.java
  src/main/java/poomasi/domain/order/controller/OrderController.java
  src/main/java/poomasi/domain/order/dto/response/OrderDetailsResponse.java
  src/main/java/poomasi/domain/order/dto/response/OrderProductDetailsResponse.java
  src/main/java/poomasi/domain/order/dto/response/OrderResponse.java
  src/main/java/poomasi/domain/order/entity/AbstractOrder.java
  src/main/java/poomasi/domain/order/entity/Order.java
  src/main/java/poomasi/domain/order/entity/OrderDetails.java
  src/main/java/poomasi/domain/order/entity/OrderProductDetails.java
  src/main/java/poomasi/domain/order/entity/OrderStatus.java
  src/main/java/poomasi/domain/order/repository/OrderProductDetailsRepository.java
  src/main/java/poomasi/domain/order/repository/OrderRepository.java
  src/main/java/poomasi/domain/order/service/OrderService.java
  src/main/java/poomasi/domain/product/_cart/controller/CartController.java
  src/main/java/poomasi/domain/product/_cart/dto/CartRegisterRequest.java
  src/main/java/poomasi/domain/product/_cart/dto/CartRequest.java
  src/main/java/poomasi/domain/product/_cart/dto/CartResponse.java
  src/main/java/poomasi/domain/product/_cart/entity/Cart.java
  src/main/java/poomasi/domain/product/_cart/repository/CartRepository.java
  src/main/java/poomasi/domain/product/_cart/service/CartService.java
  src/main/java/poomasi/domain/product/_category/controller/CategoryAdminController.java
  src/main/java/poomasi/domain/product/_category/controller/CategoryController.java
  src/main/java/poomasi/domain/product/controller/ProductFarmerController.java
  src/main/java/poomasi/domain/product/dto/ProductRegisterRequest.java
  src/main/java/poomasi/domain/product/entity/Product.java
  src/main/java/poomasi/domain/product/service/ProductFarmerService.java
  src/main/java/poomasi/domain/product/service/ProductService.java
  src/main/java/poomasi/domain/review/controller/ReviewController.java
  src/main/java/poomasi/domain/review/controller/farm/FarmReviewController.java
  src/main/java/poomasi/domain/review/controller/product/ProductReviewController.java
  src/main/java/poomasi/domain/review/dto/ReviewRequest.java
  src/main/java/poomasi/domain/review/dto/ReviewResponse.java
  src/main/java/poomasi/domain/review/entity/Review.java
  src/main/java/poomasi/domain/review/service/ReviewService.java
  src/main/java/poomasi/domain/review/service/farm/FarmReviewService.java
  src/main/java/poomasi/domain/review/service/product/ProductReviewService.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/test/java/poomasi/domain/payment/iamportTest/IamportTest.java
Labels: 🎉 feature

#73 Farm Schedule 관리 방식 및 금액제도 수정
  src/main/java/poomasi/domain/farm/_schedule/controller/FarmScheduleFarmerController.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleResponse.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleUpdateRequest.java
  src/main/java/poomasi/domain/farm/_schedule/entity/FarmSchedule.java
  src/main/java/poomasi/domain/farm/_schedule/repository/FarmScheduleRepository.java
  src/main/java/poomasi/domain/farm/_schedule/service/FarmScheduleService.java
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/reservation/dto/request/ReservationRequest.java
  src/main/java/poomasi/domain/reservation/entity/Reservation.java
  src/main/java/poomasi/domain/reservation/repository/ReservationRepository.java
  src/main/java/poomasi/domain/reservation/service/ReservationPlatformService.java
  src/main/java/poomasi/domain/reservation/service/ReservationService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🎉 feature, 🤨 P1

#71 기존 category, product, review 코드 security 적용하기
  src/main/java/poomasi/domain/product/entity/Product.java
  src/main/java/poomasi/domain/review/entity/Review.java
  src/main/java/poomasi/domain/review/service/farm/FarmReviewService.java
Labels: 🎉 feature, 😐 P2

#74 feat: 인증인가 추가
  src/main/java/poomasi/domain/farm/_schedule/controller/FarmScheduleController.java
  src/main/java/poomasi/domain/farm/_schedule/controller/FarmScheduleFarmerController.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleRequest.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleResponse.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleUpdateRequest.java
  src/main/java/poomasi/domain/farm/_schedule/entity/FarmSchedule.java
  src/main/java/poomasi/domain/farm/_schedule/repository/FarmScheduleRepository.java
  src/main/java/poomasi/domain/farm/_schedule/service/FarmScheduleService.java
  src/main/java/poomasi/domain/farm/controller/FarmFarmerController.java
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
Labels: 🎉 feature

#95 FarmSchedule 누락 사항
  src/main/java/poomasi/domain/farm/_schedule/controller/FarmSchedulePlatformController.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleResponse.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleUpdateRequest.java
  src/main/java/poomasi/domain/farm/_schedule/service/FarmScheduleService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🛳️ ship

#79 회원 조회
  src/main/java/poomasi/domain/member/controller/MemberController.java
  src/main/java/poomasi/domain/member/dto/MemberResponse.java
  src/main/java/poomasi/domain/member/dto/request/FarmerQualificationRequest.java
  src/main/java/poomasi/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/poomasi/domain/member/dto/response/MemberResponse.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/member/service/MemberService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🎉 feature

#98 예약 & 농장 조회 Security 적용
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/farm/repository/FarmRepository.java
  src/main/java/poomasi/domain/farm/service/FarmService.java
  src/main/java/poomasi/domain/member/service/MemberService.java
  src/main/java/poomasi/domain/reservation/controller/ReservationFarmerController.java
  src/main/java/poomasi/domain/reservation/controller/ReservationPlatformController.java
  src/main/java/poomasi/domain/reservation/dto/request/ReservationRequest.java
  src/main/java/poomasi/domain/reservation/entity/Reservation.java
  src/main/java/poomasi/domain/reservation/repository/ReservationRepository.java
  src/main/java/poomasi/domain/reservation/service/ReservationFarmerService.java
  src/main/java/poomasi/domain/reservation/service/ReservationPlatformService.java
  src/main/java/poomasi/domain/reservation/service/ReservationService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🐞 bug, 🛠️ enhancement

#102 [TEST] Mockito 설정 및 기본 테스트 코드 추가
  build.gradle
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/test/java/poomasi/domain/farm/FarmTestHelper.java
  src/test/java/poomasi/domain/farm/service/FarmServiceTest.java
Labels: 🛳️ ship

#105 [CICD] ECS CICD 파이프라인 구축
  .github/workflows/deploy-ecs.yml
  Dockerfile
  build.gradle
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/global/health/HealthcheckController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: CICD

#108 [예약 결제 대응] Reservation 결제 예정 금액
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/dto/FarmResponse.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/reservation/dto/request/ReservationRequest.java
  src/main/java/poomasi/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/poomasi/domain/reservation/entity/Reservation.java
Labels: 🛳️ ship

#115 [CICD] tf-prod.json 파일 추가
  .github/workflows/deploy-ecs.yml
  tf-prod.json
Labels: 🛳️ ship

#117 [CI] 테스트 실패 시 GitHub 봇 댓글 알림 기능 추가
  .github/workflows/ci-test.yml
Labels: 🔙 backlog

#112 [TEST] Farm 테스트 코드 작성
  src/main/java/poomasi/domain/member/entity/Member.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmPlatformServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmServiceTest.java
Labels: 😐 P2, 🍀 test

#104 store생성하기
  src/main/java/poomasi/domain/auth/signup/service/SignupService.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/product/_cart/entity/Cart.java
  src/main/java/poomasi/domain/product/_category/entity/Category.java
  src/main/java/poomasi/domain/product/dto/ProductRegisterRequest.java
  src/main/java/poomasi/domain/product/dto/ProductResponse.java
  src/main/java/poomasi/domain/product/entity/Product.java
  src/main/java/poomasi/domain/product/service/ProductFarmerService.java
  src/main/java/poomasi/domain/review/dto/ReviewResponse.java
  src/main/java/poomasi/domain/review/entity/Review.java
  src/main/java/poomasi/domain/store/controller/StoreController.java
  src/main/java/poomasi/domain/store/dto/StoreFeeRequest.java
  src/main/java/poomasi/domain/store/dto/StoreRegisterRequest.java
  src/main/java/poomasi/domain/store/dto/StoreResponse.java
  src/main/java/poomasi/domain/store/entity/Store.java
  src/main/java/poomasi/domain/store/repository/StoreRepository.java
  src/main/java/poomasi/domain/store/service/StoreService.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
  src/test/java/poomasi/domain/store/StoreServiceTest.java
Labels: 🎉 feature, 😐 P2, 📉 DDL Required

#110 결제 order entity 수정 및 결제 구현
  build.gradle
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/order/_aftersales/controller/CancelController.java
  src/main/java/poomasi/domain/order/_aftersales/controller/ExchangeController.java
  src/main/java/poomasi/domain/order/_aftersales/controller/RefundController.java
  src/main/java/poomasi/domain/order/_aftersales/dto/FullRefundRequest.java
  src/main/java/poomasi/domain/order/_aftersales/dto/PartialRefundRequest.java
  src/main/java/poomasi/domain/order/_aftersales/entity/_abstract/AbstractAfterSales.java
  src/main/java/poomasi/domain/order/_aftersales/entity/_farm/FarmAfterSales.java
  src/main/java/poomasi/domain/order/_aftersales/entity/_product/ProductAfterSales.java
  src/main/java/poomasi/domain/order/_aftersales/entity/_product/ProductAfterSalesDetail.java
  src/main/java/poomasi/domain/order/_aftersales/entity/_product/ProductAfterSalesType.java
  src/main/java/poomasi/domain/order/_aftersales/entity/_product/RefundExchangeDetail.java
  src/main/java/poomasi/domain/order/_aftersales/repository/ProductAfterSalesRepository.java
  src/main/java/poomasi/domain/order/_aftersales/service/RefundService.java
  src/main/java/poomasi/domain/order/_payment/controller/PaymentController.java
  src/main/java/poomasi/domain/order/_payment/dto/request/PaymentPreRegisterRequest.java
  src/main/java/poomasi/domain/order/_payment/dto/request/PaymentValidateRequest.java
  src/main/java/poomasi/domain/order/_payment/dto/request/PaymentWebHookRequest.java
  src/main/java/poomasi/domain/order/_payment/dto/response/PaymentResponse.java
  src/main/java/poomasi/domain/order/_payment/entity/Payment.java
  src/main/java/poomasi/domain/order/_payment/entity/PaymentState.java
  src/main/java/poomasi/domain/order/_payment/service/PaymentService.java
  src/main/java/poomasi/domain/order/_refund/entity/Refund.java
  src/main/java/poomasi/domain/order/_refund/entity/RefundStatus.java
  src/main/java/poomasi/domain/order/controller/OrderController.java
  src/main/java/poomasi/domain/order/dto/request/OrderRegisterRequest.java
  src/main/java/poomasi/domain/order/dto/response/OrderDetailsResponse.java
  src/main/java/poomasi/domain/order/dto/response/OrderProductDetailsResponse.java
  src/main/java/poomasi/domain/order/dto/response/OrderResponse.java
  src/main/java/poomasi/domain/order/entity/AbstractOrder.java
  src/main/java/poomasi/domain/order/entity/Order.java
  src/main/java/poomasi/domain/order/entity/OrderProductDetails.java
  src/main/java/poomasi/domain/order/entity/OrderStatus.java
  src/main/java/poomasi/domain/order/entity/_abstract/AbstractOrder.java
  src/main/java/poomasi/domain/order/entity/_farm/FarmOrder.java
  src/main/java/poomasi/domain/order/entity/_farm/FarmOrderDetails.java
  src/main/java/poomasi/domain/order/entity/_farm/OrderedFarm.java
  src/main/java/poomasi/domain/order/entity/_product/OrderedProduct.java
  src/main/java/poomasi/domain/order/entity/_product/ProductOrder.java
  src/main/java/poomasi/domain/order/entity/_product/ProductOrderDetails.java
  src/main/java/poomasi/domain/order/entity/_product/ProductsOrderDetailsStatus.java
  src/main/java/poomasi/domain/order/entity/_product/ShippingStatus.java
  src/main/java/poomasi/domain/order/repository/OrderProductDetailsRepository.java
  src/main/java/poomasi/domain/order/repository/OrderRepository.java
  src/main/java/poomasi/domain/order/repository/OrderedProductRepository.java
  src/main/java/poomasi/domain/order/repository/ProductOrderRepository.java
  src/main/java/poomasi/domain/order/service/OrderService.java
  src/main/java/poomasi/domain/product/entity/Product.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/error/ExceptionAdvice.java
  src/main/java/poomasi/global/error/PaymentConfirmError.java
  src/main/java/poomasi/global/error/PaymentConfirmException.java
Labels: 🎉 feature, 🤨 P1

#137 [TEST] FarmSchedule 테스트코드 작성
  .github/workflows/ci-test.yml
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/test/java/poomasi/domain/farm/_schedule/service/FarmScheduleServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmServiceTest.java
  src/test/java/poomasi/domain/payment/iamportTest/IamportTest.java
  src/test/java/poomasi/global/config/s3/S3PresignedUrlServiceTest.java
  src/test/resources/application-test.yml
Labels: 🍀 test

#150 [TEST] FarmSchedule 테스트코드 작성
  .github/workflows/ci-test.yml
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/test/java/poomasi/domain/farm/_schedule/service/FarmScheduleServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmServiceTest.java
  src/test/java/poomasi/domain/payment/iamportTest/IamportTest.java
  src/test/java/poomasi/global/config/s3/S3PresignedUrlServiceTest.java
  src/test/resources/application-test.yml
Labels: 🍀 test

#126 [농장] 사업자 번호 칼럼 추가
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
Labels: 🛳️ ship

#184 [STORE] 테스트코드 에러 해결
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/store/controller/StoreController.java
  src/main/java/poomasi/domain/store/service/StoreService.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/test/java/poomasi/domain/store/StoreServiceTest.java
Labels: 🐞 bug

#185 [CICD] Oauth2 Key값 추가
  .github/workflows/deploy-ecs.yml
  Dockerfile
  src/main/resources/application-prod.yml
Labels: 🏗️ CICD

#187 [농장] 카테고리 생성 및 누락 칼럼 추가
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/farm/_category/controller/FarmCategoryController.java
  src/main/java/poomasi/domain/farm/_category/domain/FarmCategory.java
  src/main/java/poomasi/domain/farm/_category/dto/response/FarmCategoryResponse.java
  src/main/java/poomasi/domain/farm/_category/repository/FarmCategoryRepository.java
  src/main/java/poomasi/domain/farm/_category/service/FarmCategoryService.java
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/global/common/ProduceType.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
Labels: 🎉 feature, 📉 DDL Required

#192 [사업자 등록] 사업자 등록증 OCR 검증 및 BIZ 프로필 추가
  .github/workflows/deploy-ecs.yml
  Dockerfile
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/member/_biz/controller/BizProfileApproveRequest.java
  src/main/java/poomasi/domain/member/_biz/controller/BizProfileFarmerController.java
  src/main/java/poomasi/domain/member/_biz/dto/request/BizProfileCreateRequest.java
  src/main/java/poomasi/domain/member/_biz/dto/response/BizProfileProfileResponse.java
  src/main/java/poomasi/domain/member/_biz/entity/MemberBizProfile.java
  src/main/java/poomasi/domain/member/_biz/repository/MemberBizProfileRepository.java
  src/main/java/poomasi/domain/member/_biz/service/MemberBizProfileFarmerService.java
  src/main/java/poomasi/domain/member/_biz/service/MemberBizProfileService.java
  src/main/java/poomasi/global/common/ImageFormat.java
  src/main/java/poomasi/global/config/client/RestClientConfig.java
  src/main/java/poomasi/global/error/ApplicationError.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/ocr/NaverOcrService.java
  src/main/java/poomasi/global/ocr/OcrService.java
  src/main/java/poomasi/global/ocr/dto/request/NaverOcrImage.java
  src/main/java/poomasi/global/ocr/dto/request/NaverOcrRequest.java
  src/main/java/poomasi/global/ocr/dto/request/OcrRequest.java
  src/main/java/poomasi/global/ocr/dto/response/ConvertedImageInfo.java
  src/main/java/poomasi/global/ocr/dto/response/NaverOcrImageResponse.java
  src/main/java/poomasi/global/ocr/dto/response/NaverOcrResponse.java
  src/main/java/poomasi/global/ocr/dto/response/OcrResponse.java
  src/main/java/poomasi/global/ocr/dto/response/ValidationResult.java
  src/main/resources/application-prod.yml
Labels: 🎉 feature, 😐 P2, 📉 DDL Required

#195 [로그인] 농부로 전환 API 엔드포인트 수정
  src/main/java/poomasi/domain/member/controller/MemberController.java
Labels: 🛳️ ship

#191 [농장] 농장 설명 추가
  src/main/java/poomasi/domain/farm/controller/FarmController.java
  src/main/java/poomasi/domain/farm/controller/FarmFarmerController.java
  src/main/java/poomasi/domain/farm/dto/request/FarmInfoRegisterRequest.java
  src/main/java/poomasi/domain/farm/dto/request/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/dto/request/FarmUpdateRequest.java
  src/main/java/poomasi/domain/farm/dto/response/FarmDetailResponse.java
  src/main/java/poomasi/domain/farm/dto/response/FarmInfoResponse.java
  src/main/java/poomasi/domain/farm/dto/response/FarmResponse.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/farm/entity/FarmInfo.java
  src/main/java/poomasi/domain/farm/repository/FarmInfoRepository.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/farm/service/FarmInfoService.java
  src/main/java/poomasi/domain/farm/service/FarmPlatformService.java
  src/main/java/poomasi/domain/farm/service/FarmService.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/test/java/poomasi/domain/farm/service/FarmFarmerServiceTest.java
  src/test/java/poomasi/domain/farm/service/FarmPlatformServiceTest.java
Labels: 🎉 feature, 😐 P2, 📉 DDL Required

#202 [CICD] Oauth2 product 환경 파일 수정
  src/main/resources/application-prod.yml
Labels: 🛳️ ship, 🏗️ CICD

#211 [농장] 농장 생성시 시작날짜/종료날짜/시작시간/종료날짜
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleResponse.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleUpdateRequest.java
  src/main/java/poomasi/domain/farm/_schedule/entity/FarmSchedule.java
  src/main/java/poomasi/domain/farm/_schedule/entity/ScheduleStatus.java
  src/main/java/poomasi/domain/farm/_schedule/repository/FarmScheduleRepository.java
  src/main/java/poomasi/domain/farm/_schedule/service/FarmScheduleService.java
  src/main/java/poomasi/domain/farm/dto/request/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/dto/response/FarmDetailResponse.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/farm/service/FarmInfoService.java
  src/main/java/poomasi/domain/farm/service/FarmPlatformService.java
Labels: 😐 P2

#234 [TEST] 농장 예약 관련 테스트 코드
  src/main/java/poomasi/domain/farm/_schedule/entity/FarmSchedule.java
  src/main/java/poomasi/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/poomasi/domain/reservation/entity/Reservation.java
  src/test/java/poomasi/domain/reservation/service/ReservationFarmerServiceTest.java
  src/test/java/poomasi/domain/reservation/service/ReservationPlatformServiceTest.java
Labels: 🍀 test
