Repository kakao-tech-campus-2nd-step3/Team10_BE, pull requests merged in 2024-10, with the labels that each got.

#23 Redis 수정
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/auth/controller/AuthController.java
  src/main/java/poomasi/domain/auth/dto/request/TokenRequest.java
  src/main/java/poomasi/domain/auth/entity/RefreshToken.java
  src/main/java/poomasi/domain/auth/service/AuthService.java
  src/main/java/poomasi/domain/auth/service/RefreshTokenService.java
  src/main/java/poomasi/domain/member/controller/MemberController.java
  src/main/java/poomasi/domain/member/service/MemberService.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/redis/config/RedisConfig.java
  src/main/java/poomasi/global/redis/error/RedisConnectionException.java
  src/main/java/poomasi/global/redis/error/RedisOperationException.java
  src/main/java/poomasi/global/redis/service/RedisService.java
  src/main/java/poomasi/global/util/JwtUtil.java
  src/main/resources/application-secret.yml
Labels: 😐 P2

#18 Product, Category Entity
  src/main/java/poomasi/domain/category/controller/CategoryAdminController.java
  src/main/java/poomasi/domain/category/controller/CategoryController.java
  src/main/java/poomasi/domain/category/dto/CategoryRequest.java
  src/main/java/poomasi/domain/category/dto/CategoryResponse.java
  src/main/java/poomasi/domain/category/entity/Category.java
  src/main/java/poomasi/domain/category/repository/CategoryRepository.java
  src/main/java/poomasi/domain/category/service/CategoryAdminService.java
  src/main/java/poomasi/domain/category/service/CategoryService.java
  src/main/java/poomasi/domain/farm/controller/FarmController.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/farm/service/FarmService.java
  src/main/java/poomasi/domain/product/controller/ProductAdminController.java
  src/main/java/poomasi/domain/product/controller/ProductFarmerController.java
  src/main/java/poomasi/domain/product/dto/ProductListResponse.java
  src/main/java/poomasi/domain/product/dto/ProductRegisterRequest.java
  src/main/java/poomasi/domain/product/entity/Product.java
  src/main/java/poomasi/domain/product/repository/ProductRepository.java
  src/main/java/poomasi/domain/product/service/ProductAdminService.java
  src/main/java/poomasi/domain/product/service/ProductFarmerService.java
  src/main/java/poomasi/global/error/ApplicationError.java
  src/main/java/poomasi/global/error/ApplicationException.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/error/BusinessException.java
  src/main/java/poomasi/global/error/ExceptionAdvice.java
Labels: 🎉 feature, 🤨 P1, 📉 DDL Required

#30 농장 예약 가능 시간대 등록 및 조회
  src/main/java/poomasi/domain/farm/_schedule/controller/FarmScheduleController.java
  src/main/java/poomasi/domain/farm/_schedule/controller/FarmScheduleFarmerController.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleRequest.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleResponse.java
  src/main/java/poomasi/domain/farm/_schedule/dto/FarmScheduleUpdateRequest.java
  src/main/java/poomasi/domain/farm/_schedule/entity/FarmSchedule.java
  src/main/java/poomasi/domain/farm/_schedule/entity/ScheduleStatus.java
  src/main/java/poomasi/domain/farm/_schedule/repository/FarmScheduleRepository.java
  src/main/java/poomasi/domain/farm/_schedule/service/FarmScheduleService.java
  src/main/java/poomasi/domain/farm/controller/FarmController.java
  src/main/java/poomasi/domain/farm/controller/FarmFarmerController.java
  src/main/java/poomasi/domain/farm/dto/FarmRegisterRequest.java
  src/main/java/poomasi/domain/farm/dto/FarmResponse.java
  src/main/java/poomasi/domain/farm/entity/Farm.java
  src/main/java/poomasi/domain/farm/repository/FarmRepository.java
  src/main/java/poomasi/domain/farm/service/FarmFarmerService.java
  src/main/java/poomasi/domain/farm/service/FarmService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🎉 feature, 🤨 P1, 📉 DDL Required

#34 username / jwt 인증 filter 구현
  build.gradle
  src/main/java/poomasi/domain/auth/config/SecurityBeanGenerator.java
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/auth/security/filter/CustomLogoutFilter.java
  src/main/java/poomasi/domain/auth/security/filter/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/poomasi/domain/auth/security/filter/JwtAuthenticationFilter.java
  src/main/java/poomasi/domain/auth/security/userdetail/UserDetailsImpl.java
  src/main/java/poomasi/domain/auth/security/userdetail/UserDetailsServiceImpl.java
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/member/entity/Role.java
Labels: 🛠️ enhancement, 🎉 feature, 🤨 P1

#48 fix : bug 수정
  src/main/java/poomasi/domain/auth/config/SecurityBeanGenerator.java
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/auth/security/filter/CustomLogoutFilter.java
  src/main/java/poomasi/domain/auth/security/filter/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/poomasi/domain/auth/security/filter/JwtAuthenticationFilter.java
Labels: 🐞 bug

#50 리프레시 토큰 관리 리팩토링
  src/main/java/poomasi/domain/auth/reissue/manager/TokenType.java
  src/main/java/poomasi/domain/auth/reissue/service/ReissueTokenService.java
  src/main/java/poomasi/domain/auth/signup/controller/SignupController.java
  src/main/java/poomasi/domain/auth/signup/service/SignupService.java
  src/main/java/poomasi/domain/auth/util/JwtUtil.java
  src/main/java/poomasi/domain/member/entity/MemberProfile.java
Labels: 🛠️ enhancement

#51 S3 설정 및 Presigned URL 관련 메소드 정의
  build.gradle
  src/main/java/poomasi/global/config/aws/AwsProperties.java
  src/main/java/poomasi/global/config/s3/S3Config.java
  src/main/java/poomasi/global/config/s3/S3PresignedUrlService.java
  src/main/java/poomasi/global/config/s3/TestController.java
  src/main/java/poomasi/global/error/ApplicationError.java
  src/main/java/poomasi/global/util/EncryptionUtil.java
  src/test/java/poomasi/global/config/s3/S3PresignedUrlServiceTest.java
Labels: 🎉 feature, 🤨 P1

#43 Review 만들기
  src/main/java/poomasi/domain/product/_category/controller/CategoryAdminController.java
  src/main/java/poomasi/domain/product/_category/controller/CategoryController.java
  src/main/java/poomasi/domain/product/_category/dto/CategoryRequest.java
  src/main/java/poomasi/domain/product/_category/dto/CategoryResponse.java
  src/main/java/poomasi/domain/product/_category/dto/ProductListInCategoryResponse.java
  src/main/java/poomasi/domain/product/_category/entity/Category.java
  src/main/java/poomasi/domain/product/_category/service/CategoryAdminService.java
  src/main/java/poomasi/domain/product/_category/service/CategoryService.java
  src/main/java/poomasi/domain/product/controller/ProductAdminController.java
  src/main/java/poomasi/domain/product/controller/ProductController.java
  src/main/java/poomasi/domain/product/controller/ProductFarmerController.java
  src/main/java/poomasi/domain/product/dto/ProductListResponse.java
  src/main/java/poomasi/domain/product/dto/ProductRegisterRequest.java
  src/main/java/poomasi/domain/product/dto/ProductResponse.java
  src/main/java/poomasi/domain/product/dto/UpdateProductQuantityRequest.java
  src/main/java/poomasi/domain/product/entity/Product.java
  src/main/java/poomasi/domain/product/repository/ProductRepository.java
  src/main/java/poomasi/domain/product/service/ProductAdminService.java
  src/main/java/poomasi/domain/product/service/ProductFarmerService.java
  src/main/java/poomasi/domain/product/service/ProductService.java
  src/main/java/poomasi/domain/review/controller/ReviewController.java
  src/main/java/poomasi/domain/review/controller/farm/FarmReviewController.java
  src/main/java/poomasi/domain/review/controller/product/ProductReviewController.java
  src/main/java/poomasi/domain/review/dto/ReviewRequest.java
  src/main/java/poomasi/domain/review/dto/ReviewResponse.java
  src/main/java/poomasi/domain/review/entity/EntityType.java
  src/main/java/poomasi/domain/review/entity/Review.java
  src/main/java/poomasi/domain/review/repository/ReviewRepository.java
  src/main/java/poomasi/domain/review/service/ReviewService.java
  src/main/java/poomasi/domain/review/service/farm/FarmReviewService.java
  src/main/java/poomasi/domain/review/service/product/ProductReviewService.java
  src/main/java/poomasi/global/error/ApplicationException.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/error/BusinessException.java
Labels: 🎉 feature, 😐 P2, 📉 DDL Required

#58 위시리스트를 생성한다
  src/main/java/poomasi/domain/member/entity/Member.java
  src/main/java/poomasi/domain/product/service/ProductService.java
  src/main/java/poomasi/domain/wishlist/controller/WishListPlatformController.java
  src/main/java/poomasi/domain/wishlist/dto/WishListDeleteRequest.java
  src/main/java/poomasi/domain/wishlist/dto/WishListResponse.java
  src/main/java/poomasi/domain/wishlist/dto/request/WishListAddRequest.java
  src/main/java/poomasi/domain/wishlist/entity/WishList.java
  src/main/java/poomasi/domain/wishlist/repository/WishListRepository.java
  src/main/java/poomasi/domain/wishlist/service/WishListPlatformService.java
  src/main/java/poomasi/domain/wishlist/service/WishListService.java
  src/main/java/poomasi/global/error/ApplicationException.java
  src/main/java/poomasi/global/error/BusinessError.java
  src/main/java/poomasi/global/error/BusinessException.java
Labels: 🎉 feature, 🤨 P1

#68 jwt filter 버그 수정
  src/main/java/poomasi/domain/auth/config/SecurityConfig.java
  src/main/java/poomasi/domain/auth/security/AuthTestController.java
  src/main/java/poomasi/domain/auth/security/AuthTestService.java
  src/main/java/poomasi/domain/auth/security/filter/JwtAuthenticationFilter.java
Labels: 🐞 bug

#66 feat : 장바구니 crud, test완료
  src/main/java/poomasi/domain/product/_cart/controller/CartController.java
  src/main/java/poomasi/domain/product/_cart/dto/CartRegisterRequest.java
  src/main/java/poomasi/domain/product/_cart/dto/CartRequest.java
  src/main/java/poomasi/domain/product/_cart/dto/CartResponse.java
  src/main/java/poomasi/domain/product/_cart/entity/Cart.java
  src/main/java/poomasi/domain/product/_cart/repository/CartRepository.java
  src/main/java/poomasi/domain/product/_cart/service/CartService.java
  src/main/java/poomasi/global/error/BusinessError.java
Labels: 🎉 feature, 😐 P2
